alias l='ls -lh --group-directories-first'
alias ll='ls -lAh --group-directories-first'
alias service='sudo service'
alias home='cd ~/'
alias art='php artisan'
alias dbr='php artisan migrate:rollback && php artisan migrate --seed'